### ISSUE TITLE
[Bug] IAppHostBuilder lost method after Microsoft.MAUI package update from 4.634 to 5.794 

### ISSUE THREAD

**Issue by julajus** [dotnet/maui#1338]
When updated Microsoft.MAUI package from 6.0.100-preview.4.634 to 6.0.100-preview.5.794, IAppHostBuilder does not contain method UseFormsCompatibility().
Used in MAUI example applications Startup class, Configure(IAppHostBuilder appBuilder) method.

### Steps to Reproduce

1. Create new MAUI hello world application (used Microsoft.MAUI 6.0.100-preview.4.634)
2. Update Microsoft.MAUI to 6.0.100-preview.5.794
3. Project build failed (Error CS1061 'IAppHostBuilder' does not contain a definition for 'UseFormsCompatibility' and no accessible extension method 'UseFormsCompatibility' accepting a first argument of type 'IAppHostBuilder' could be found)

- Version with issue:
- Last known good version: Microsoft.MAUI 6.0.100-preview.4.634
- IDE:
- Platform Target Frameworks: any
  - iOS:  any
  - Android: any
  - UWP:  any
- Android Support Library Version: any
- Nuget Packages: 
MauiApp:
![image](https://user-images.githubusercontent.com/46684724/122354148-65afef80-cf59-11eb-863f-aebd0b8501da.png)
MauiApp.WinUI3
![image](https://user-images.githubusercontent.com/46684724/122353952-339e8d80-cf59-11eb-8ab2-4debca2185a4.png)
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/46684724/122353807-15389200-cf59-11eb-8db8-40f5d1ef5f80.png)

**Comment by yamachu** [comment]
see: https://github.com/dotnet/maui/pull/1292
It seems like it can be deleted.

**Comment by dansiegel** [comment]
Yeah that's not a bug. Good tip for you is to remember this is a preview lots of things are changing. As they release a new preview create a new Maui project to see what's changed with the project structure and startup.

**Comment by lutzroeder** [comment]
Duplicate of #1397
