### ISSUE TITLE
Upgrading maui ios from 7.0.81 to 7.0.86 causes error build with dotnet ios 16.2

### ISSUE THREAD

**Issue by yunusefendi52** [dotnet/maui#15123]
### Description

I am trying to build some projects. I already installed dotnet 7, dotnet ios 16.2 and xcode 14.2

Upgrading maui ios from 7.0.81 to 7.0.86 causes this error:
```
/Users/yunus/deducted/CSC: Error CS1705: Assembly 'Microsoft.Maui' with identity 'Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.iOS, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version than referenced assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=16.2.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' (CS1705)
```

It seems maui 7.0.81 has minimum dotnet ios 16.2 whereas 7.0.86 has minimum dotnet ios 16.4, is it possible to set the minimum version to the lowest version? I was thinking specify the target framework with version
```csproj
<TargetFrameworks>net7.0-ios16.0</TargetFrameworks>
```

I already raise this issue but the answer did not make sense because we still can set minimum version to lowest version. #13183

### Steps to Reproduce

1. Install dotnet 7
2. Install dotnet maui 7.0.81 (dotnet workload install maui --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/7.0.81.json)
3. Install dotnet maui 7.0.86 **only, without installing other workloads**
4. Create maui project and see the build error

### Link to public reproduction project repository

can't

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

No

### Relevant log output

```shell
/Users/yunus/Documents/P/irismobile/Code/IrisMobile/CSC: Error CS1705: Assembly 'Microsoft.Maui' with identity 'Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.iOS, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version than referenced assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=16.2.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' (CS1705) (IrisMobile)
```
