### ISSUE TITLE
 error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'Microsoft.Maui.Controls.Compatibility.Platform'

### ISSUE THREAD

**Issue by febinDonz** [dotnet/maui#20589]
### Description

Getting error when trying to build with Pipelines.
Builds were working fine in Maui version 8.0.101

New pipeline is using 8.0.200.

### Steps to Reproduce

Build Maui ios app using Pipelines.

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.6 SR1

### Affected platforms

iOS

### Did you find any workaround?

No

### Relevant log output

```shell
/Users/runner/work/1/s/TestProject/MauiProgram.cs(12,54): error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'Microsoft.Maui.Controls.Compatibility.Platform' (are you missing an assembly reference?) [/Users/runner/work/1/s/TestProject/TestProject.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/TestProject/Platforms/iOS/PlatformSpecific/DisclosureIndicatorRenderer.cs(2,40): error CS0234: The type or namespace name 'Compatibility' does not exist in the namespace 'Microsoft.Maui.Controls.Handlers' (are you missing an assembly reference?) [/Users/runner/work/1/s/TestProject/TestProject.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/TestProject/Platforms/iOS/AppDelegate.cs(14,28): error CS0246: The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/1/s/TestProject/TestProject.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/TestProject/Helpers/Controls/Label.cs(14,49): warning CS0108: 'Label.MaxLinesProperty' hides inherited member 'Label.MaxLinesProperty'. Use the new keyword if hiding was intended. [/Users/runner/work/1/s/TestProject/TestProject.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/TestProject/Helpers/Controls/Label.cs(15,20): warning CS0108: 'Label.MaxLines' hides inherited member 'Label.MaxLines'. Use the new keyword if hiding was intended. [/Users/runner/work/1/s/TestProject/TestProject.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/TestProject/Helpers/Controls/Label.cs(21,49): warning CS0108: 'Label.TextTypeProperty' hides inherited member 'Label.TextTypeProperty'. Use the new keyword if hiding was intended. [/Users/runner/work/1/s/TestProject/TestProject.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/TestProject/Helpers/Controls/Label.cs(22,30): warning CS0108: 'Label.TextType' hides inherited member 'Label.TextType'. Use the new keyword if hiding was intended. [/Users/runner/work/1/s/TestProject/TestProject.csproj::TargetFramework=net8.0-ios]
```

**Comment by domneedham** [comment]
I think related to this, I am seeing the following issue with both macOS and iOS using the latest dotnet version:

/namespace/Platforms/MacCatalyst/CustomControls/CustomButtonHandler.cs(29,29): Error CS0115: 'CustomButtonHandler.ConnectHandler(UIButton)': no suitable method found to override (CS0115)

```csharp
    protected override void ConnectHandler(UIButton platformView)
    {
        base.ConnectHandler(platformView);

        platformView.Layer.CornerRadius = 3;
        platformView.Layer.BorderWidth = 2;
        platformView.Layer.BorderColor = Colors.Transparent.ToCGColor();
    }

```

This was working fine beforehand with dotnet 8.0.0
