### ISSUE TITLE
MAUI-WinUI app crashes/cannot attach debugger after updating maui workload

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#26590]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-WinUI-app-crashescannot-attach-deb/10785972)._

---
![Screenshot 2024-11-08 095649-winUI-maui-app-crash.png](https://aka.ms/dc/image?name=Baec67c2be8214b28a274d5a2f6d167aa638666783465178641_Screenshot_2024-11-08_095649-winUI-maui-app-crash.png&tid=aec67c2be8214b28a274d5a2f6d167aa638666783465178641)

This started after running `dotnet workload install maui --version 8.0.402.0` to resolve a different issue (not sure if the other issue is related, or if seperate?)

The original issue was a linker error when trying to build maui-ios app via connected mac system, where I _can_ build the same solution on the mac locally, using Rider, but this was occurring with VS on Windows:

```  
1&gt;C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_18.0\18.0.8303\targets\Xamarin.Shared.Sdk.targets(1643,3): error : clang++ exited with code 1:
1&gt;C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_18.0\18.0.8303\targets\Xamarin.Shared.Sdk.targets(1643,3): error : Undefined symbols for architecture arm64:
1&gt;C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_18.0\18.0.8303\targets\Xamarin.Shared.Sdk.targets(1643,3): error :   "_xamarin_is_object_valid", referenced from:
1&gt;C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_18.0\18.0.8303\targets\Xamarin.Shared.Sdk.targets(1643,3): error :       &lt;initial-undefines&gt;
1&gt;C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_18.0\18.0.8303\targets\Xamarin.Shared.Sdk.targets(1643,3): error :   "_xamarin_is_user_type", referenced from:
1&gt;C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_18.0\18.0.8303\targets\Xamarin.Shared.Sdk.targets(1643,3): error :       &lt;initial-undefines&gt;
1&gt;C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_18.0\18.0.8303\targets\Xamarin.Shared.Sdk.targets(1643,3): error : ld: symbol(s) not found for architecture arm64
1&gt;C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_18.0\18.0.8303\targets\Xamarin.Shared.Sdk.targets(1643,3): error : clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  
```

The iOS 18 SDK _should not_ be required, with `maui --version 8.0.402.0`, but for some reason, VS on Windows was trying to build with `maui --version 8.0.402.1` or newer?

After uninstalling VS and all .Net 8 SDK’s, I re-installed VS 17.11.3, and now iOS builds and debugs, but _still_ WinUI throws at start of app, when/before debugger can attach (see screenshot). The only thing I see in windows error log is a fault code: “Exception code: 0xc000027b”

Immediately after VS install and loading the solution, I got a message from VS to install workloads, which I did. This installed a new workload that I haven’t seen before (wasi-experimental). This is what is currently installed.

```  
dotnet workload list

Workload version: 8.0.400-manifests.83154722

Installed Workload Id      Installation Source
----------------------------------------------------------
android                    SDK 8.0.400, VS 17.11.35303.130
ios                        SDK 8.0.400, VS 17.11.35303.130
maccatalyst                SDK 8.0.400, VS 17.11.35303.130
maui-windows               SDK 8.0.400, VS 17.11.35303.130
wasi-experimental          SDK 8.0.400
  
```

I also installed .Net SDk v 4.0.403 from winget (trying to resolve the WinUI issue).

```  
winget list --tag .Net
Name                                  Id                         Version Source
--------------------------------------------------------------------------------
Microsoft .NET Runtime - 6.0.35 (x64) Microsoft.DotNet.Runtime.6 6.0.35  winget
Microsoft .NET SDK 8.0.403 (x64)      Microsoft.DotNet.SDK.8     8.0.403 winget
PS C:\Source\Repos\Maui.ManualCropApp&gt; dotnet --list-sdks
8.0.400 [C:\Program Files\dotnet\sdk]
8.0.403 [C:\Program Files\dotnet\sdk]
  
```

Note: Most of the dev work on this project was done in VS 17.11.0 preview-3, on windows 11 build22621 using WinUI as the primary testing environment, which was working without issue until I tried to fix the iOS build issue.  
Repo: [https://xdevapps.visualstudio.com/DefaultCollection/XDev.Maui.ManualCrop/\_git/XDev.Maui.ManualCrop](https://xdevapps.visualstudio.com/DefaultCollection/XDev.Maui.ManualCrop/_git/XDev.Maui.ManualCrop)

---
#### philip bray on 11/8/2024, 00:34 PM: 

<p>Are you using skiasharp?</p>

#### joshua.sells on 11/8/2024, 00:38 PM: 

<p>re: Are you using skiasharp</p>
<p>Yes</p>

#### Feedback Bot on 11/10/2024, 07:02 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### joshua.sells on 11/18/2024, 08:18 AM: 

<p>Update:  I noticed since posting this that I <em>can</em> still debug WinUI apps, it appears if the Maui solution uses the project/platform scheme instead of the default shared-project template referenced in the OP.</p>
<p>I have another solution that uses this <a target='_blank' href="https://github.com/mattleibow/MultiHeadMauiTemplates">template</a> (the old XForms-way of a project for each target platform), and I can debug WinUI, Android, and iOS on the same system that is showing the issue above.</p>

**Comment by jasells** [comment]
I don't know exactly what changed other than system restarts/Windows updates, but the issue seems to have resolved itself without  any changes to Visual Studio or .Net SDK installs...

**Comment by jfversluis** [comment]
As much as I hate issues that magically resolve themselves... I'm glad its working for you again! Thanks for letting us know!
