### ISSUE TITLE
BindingList-BindableLayout not updating

### ISSUE THREAD

**Issue by szv** [dotnet/maui#10570]
### Description

When using a _BindingList_ as an _ItemSource_ of a _BindableLayout_, changes being made in the _BindingList_ don't get reflected in the _BindableLayout_.

v6.0.540

### Steps to Reproduce

1. Create a  _VerticalStackLayout_ with a _BindableLayout_
2. Bind the _ItemsSource_ of the _BindableLayout_ to a _BindingList_
3. Add items to the _BindingList_

Optionally you can do the same with an ObservableCollection. Then it works.

### Link to public reproduction project repository

[Github Repository](https://github.com/szv/MAUIBindableLayoutBindingListBugSample)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Tested on Windows 11 and Android 12.1 (Emulator)

### Did you find any workaround?

Using an _ObservableCollection_ instead is possible. In some cases a _BindingList_ might be more convenient though.

### Relevant log output

```shell
❌
```

**Comment by PureWeen** [comment]
Does `BindingList` implement `INotifyCollectionChanged` ?

**Comment by GalaxiaGuy** [comment]
`BindingList` looks like an old API (it has been available since NET Framework 2.0 and the interface `IBindingList` has been around since 1.0 apparently).

`BindingList<T>`: https://apisof.net/catalog/f0abaf55-4ca7-cc12-8a0c-d2ccb5c7b553
`IBindingList`: https://apisof.net/catalog/edd188ab17a306d1eac8d67f03b819fd

I've never seen it used, and would guess it has been supplanted by `INotifyCollectionChanged` (and it's common implementation `ObservableCollection<T>`.

**Comment by szv** [comment]
`BindingList` does not implement `INotifyCollectionChanged`. Nevertheless in WinUI and WPF it works as expected.

I know that `BindingList` is quite old and `ObservableCollection` is more common, but `ObservableCollection` is also quite old and in some situations the `BindingList` might be convenient though.
https://learn.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.observablecollection-1?view=net-7.0#applies-to
vs
https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.bindinglist-1?view=net-7.0#applies-to

The `BindingList` forwards `INotifyPropertyChanged`-events and with `ObservableCollection` I need to handle the events myself (which is also ok for me).

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. This issue works on iOS 16.4, but some layout issues on Android 13.0-API33.
[MauiViewUpdateBug.zip](https://github.com/dotnet/maui/files/11609514/MauiViewUpdateBug.zip)

iOS:
![Rotate](https://github.com/dotnet/maui/assets/97647558/0dbc563f-2e1b-40a7-94f9-416eaff2e1b3)

Android:
1. Starting the app in Portrait mode
![image](https://github.com/dotnet/maui/assets/97647558/666fccfc-b6f5-4415-a16b-5eebe3eb1f39)
2. Rotating into Landscape mode
![image](https://github.com/dotnet/maui/assets/97647558/340e64ce-23fb-4e18-8b02-f5038633ec5e)
3. Press the Button
![image](https://github.com/dotnet/maui/assets/97647558/01507f46-1cc2-4325-9545-6182ccfed143)
4. Rotating back into Portrait mode
![image](https://github.com/dotnet/maui/assets/97647558/4065fe51-a09d-41d8-84e1-97409b5093ee)

**Comment by kubaflo** [comment]
The report is explained by the collection contract: BindableLayout observes INotifyCollectionChanged, while the reported BindingList path does not provide that notification behavior.

Closing because the thread is resolved as usage guidance rather than actionable framework work.

**Comment by kubaflo** [comment]
Reopening — this issue should not have been closed.

It carries `s/verified` (a maintainer or partner reproduced it), `s/triaged` (it already went through triage). Those labels mean the report was already confirmed as a real product defect, so it is not eligible for backlog cleanup closure. Closure here requires specific fix evidence (a merged PR that closes it, or a `fixed-in-*` label), and there was none.

Sorry for the noise, and thanks to everyone who flagged it.

> Disclosure: this comment was generated by AI.
